name: "SimpleQA"
description: "A flow that answers questions."
model: "gpt-3.5-turbo"

input_key: [question]

system_message_prompt_template:
  template: |2-
    You are a helpful chatbot that truthfully answers questions.
  input_variables: []

query_message_prompt_template:
  template: |2-
    Answer the following question: {{question}}
  input_variables: ["question"]