run_dir: note_len_vs_note_memory

ablations: 
  - agent_1_note_max_len
  - agent_2_note_max_len
  - agent_1_msg_input_note_history
  - agent_2_msg_input_note_history
  - num_issues


metrics: 
  - 'number_rounds'
  - 'mean_issue_following'
  - 'internal_faithfulness'
  - 'external_faithfulness'
  - 'total_msg_tokens'
  - note_instr_following

sort_by:   
  - "agent_1_normalized_payoff"
  - 'agent_2_normalized_payoff'
  - total_payoff

plot:
  _target_: plots.