run_dir: optimal-parameters

ablations: 
  - num_issues

metrics: 
  - 'number_rounds'
  - 'mean_issue_following'
  - 'internal_faithfulness'
  - 'external_faithfulness'
  - 'total_msg_tokens'
  - note_instr_following
  - completion_rate