job_logging:
  handlers:
    file:
      # relative to the job log directory
      filename: ${hydra:runtime.output_dir}/stdout_${hydra.job.name}_${now:%Y-%m-%d}_${now:%H-%M-%S}.log

# output paths for hydra logs
run:
  dir: logs/${experiment_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S-%f}

verbose: False

sweep:
  dir: logs/${experiment_name}/multiruns/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}